name: Docker Image CI

on:
  # push:
  #   branches: [ "main" ]
  workflow_dispatch:
    branches: [ "main" ]
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
        type: choice
        options:
        - info
        - warning
        - debug
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Delete huge unnecessary tools folder
      run: | 
        df -h |grep /dev/root
        du -shc /*
        rm -rf /opt/hostedtoolcache
        df -h| grep /dev/root

    - uses: actions/checkout@v3
    - name: Build the Docker image
      working-directory: sd-auto-unified
#      run: echo "disabled"
      run: docker build . --file Dockerfile --tag custome-auto1111:$(date +%s)
  